### ISSUE TITLE
Support calendar integration for upcoming events

### ISSUE THREAD

**Issue by zieren** [zieren/eltern-emailer#55]
Would be cool to generate .ics files with the upcoming event notification email.

**Comment by pimisen** [comment]
This would be the gretest feature ever and much appreciated!

**Comment by zieren** [comment]
It turns out ICS files can actually delete an existing event, which is identified via a UID:

https://stackoverflow.com/questions/10551764/how-to-cancel-an-calendar-event-using-ics-files
https://community.n8n.io/t/create-a-icalendar-ics-file-with-method-cancel-to-remove-event-from-calendar/31205
https://icalendar.org/New-Properties-for-iCalendar-RFC-7986/5-3-uid-property.html

If this works and we can specify a UID on creation and store it with our state, this solves the question of how to handle deleted events.

**Comment by zieren** [comment]
I played around with it a bit but couldn't get Google Calendar to delete an event.

**Comment by zieren** [comment]
Event removal is a rare occurrence, so this should not be a show-stopper. [This page](https://support.google.com/calendar/thread/81344786/how-do-i-generate-add-to-calendar-link-from-our-own-website?hl=en) has some examples on how to create events simply from a URL, which would be easier than .ics import. There is mention of event IDs, so maybe deletion is even possible.
